package net.phreakocious.httpgraph;

import java.awt.Desktop;
import java.net.URL;
import org.netbeans.validation.api.builtin.Validators;
import org.netbeans.validation.api.ui.ValidationGroup;
import org.netbeans.validation.api.ui.ValidationPanel;
import javax.swing.JPanel;
import org.openide.util.Exceptions;


/**
 *
 * @author phreakocious
 */
public class HttpGraphPanel extends JPanel {

    private static final long serialVersionUID = 1L;

    public HttpGraphPanel() {
        initComponents();
        startLayout.setEnabled(true);
    }

    @SuppressWarnings("unchecked")
    public static ValidationPanel createValidationPanel(HttpGraphPanel innerPanel) {
        ValidationPanel validationPanel = new ValidationPanel();
        if (innerPanel == null) {
            innerPanel = new HttpGraphPanel();
        }
        validationPanel.setInnerComponent(innerPanel);

        ValidationGroup group = validationPanel.getValidationGroup();

        group.add(innerPanel.portField, Validators.REQUIRE_NON_EMPTY_STRING,
                Validators.REQUIRE_VALID_INTEGER,
                Validators.numberRange(1, 65535));

        group.add(innerPanel.restField, Validators.REQUIRE_NON_EMPTY_STRING,
                Validators.REQUIRE_VALID_INTEGER,
                Validators.numberRange(1, 65535));

        return validationPanel;
    }

    public static void openWebpage(String urlString) {
	    try {
		    Desktop.getDesktop().browse(new URL(urlString).toURI());
	    } catch (Exception e) {
		    Exceptions.printStackTrace(e);
	    }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                portLabel = new javax.swing.JLabel();
                portField = new javax.swing.JTextField();
                jLabel1 = new javax.swing.JLabel();
                startLayout = new javax.swing.JCheckBox();
                clientLabels = new javax.swing.JCheckBox();
                hostLabels = new javax.swing.JCheckBox();
                resourceLabels = new javax.swing.JCheckBox();
                jLabel2 = new javax.swing.JLabel();
                domainLabels = new javax.swing.JCheckBox();
                jLabel3 = new javax.swing.JLabel();
                jScrollPane2 = new javax.swing.JScrollPane();
                jTextArea1 = new javax.swing.JTextArea();
                jButton1 = new javax.swing.JButton();
                jButton2 = new javax.swing.JButton();
                restField = new javax.swing.JTextField();
                restLabel = new javax.swing.JLabel();

                portLabel.setText(org.openide.util.NbBundle.getMessage(HttpGraphPanel.class, "HttpGraphPanel.portLabel.text")); // NOI18N

                portField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
                portField.setText(org.openide.util.NbBundle.getMessage(HttpGraphPanel.class, "HttpGraphPanel.portField.text")); // NOI18N
                portField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                portFieldActionPerformed(evt);
                        }
                });

                jLabel1.setText(org.openide.util.NbBundle.getMessage(HttpGraphPanel.class, "HttpGraphPanel.jLabel1.text")); // NOI18N

                startLayout.setSelected(true);
                startLayout.setText(org.openide.util.NbBundle.getMessage(HttpGraphPanel.class, "HttpGraphPanel.startLayout.text")); // NOI18N
                startLayout.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                startLayoutActionPerformed(evt);
                        }
                });

                clientLabels.setSelected(true);
                clientLabels.setText(org.openide.util.NbBundle.getMessage(HttpGraphPanel.class, "HttpGraphPanel.clientLabels.text")); // NOI18N
                clientLabels.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                clientLabelsActionPerformed(evt);
                        }
                });

                hostLabels.setSelected(true);
                hostLabels.setText(org.openide.util.NbBundle.getMessage(HttpGraphPanel.class, "HttpGraphPanel.hostLabels.text")); // NOI18N
                hostLabels.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                hostLabelsActionPerformed(evt);
                        }
                });

                resourceLabels.setText(org.openide.util.NbBundle.getMessage(HttpGraphPanel.class, "HttpGraphPanel.resourceLabels.text")); // NOI18N
                resourceLabels.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                resourceLabelsActionPerformed(evt);
                        }
                });

                jLabel2.setText(org.openide.util.NbBundle.getMessage(HttpGraphPanel.class, "HttpGraphPanel.jLabel2.text")); // NOI18N

                domainLabels.setSelected(true);
                domainLabels.setText(org.openide.util.NbBundle.getMessage(HttpGraphPanel.class, "HttpGraphPanel.domainLabels.text")); // NOI18N

                jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
                jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel3.setText(org.openide.util.NbBundle.getMessage(HttpGraphPanel.class, "HttpGraphPanel.jLabel3.text")); // NOI18N

                jTextArea1.setEditable(false);
                jTextArea1.setColumns(20);
                jTextArea1.setLineWrap(true);
                jTextArea1.setRows(5);
                jTextArea1.setText(org.openide.util.NbBundle.getMessage(HttpGraphPanel.class, "HttpGraphPanel.jTextArea1.text")); // NOI18N
                jScrollPane2.setViewportView(jTextArea1);

                jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
                jButton1.setText(org.openide.util.NbBundle.getMessage(HttpGraphPanel.class, "HttpGraphPanel.jButton1.text")); // NOI18N
                jButton1.setToolTipText(org.openide.util.NbBundle.getMessage(HttpGraphPanel.class, "HttpGraphPanel.jButton1.toolTipText")); // NOI18N
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                jButton2.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
                jButton2.setText(org.openide.util.NbBundle.getMessage(HttpGraphPanel.class, "HttpGraphPanel.jButton2.text")); // NOI18N
                jButton2.setToolTipText(org.openide.util.NbBundle.getMessage(HttpGraphPanel.class, "HttpGraphPanel.jButton2.toolTipText")); // NOI18N
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton2ActionPerformed(evt);
                        }
                });

                restField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
                restField.setText(org.openide.util.NbBundle.getMessage(HttpGraphPanel.class, "HttpGraphPanel.restField.text")); // NOI18N
                restField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                restFieldActionPerformed(evt);
                        }
                });

                restLabel.setText(org.openide.util.NbBundle.getMessage(HttpGraphPanel.class, "HttpGraphPanel.restLabel.text")); // NOI18N

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addGap(41, 41, 41)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(startLayout)
                                                                        .addComponent(jLabel2)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(clientLabels)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(domainLabels)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(hostLabels)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(resourceLabels)))
                                                                .addGap(37, 37, 37))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(restLabel)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(restField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(portLabel)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(portField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(17, 17, 17))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(jLabel1))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jButton1)
                                                        .addComponent(jButton2))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(restField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(restLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(portField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(portLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(startLayout)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(clientLabels)
                                                        .addComponent(hostLabels)
                                                        .addComponent(domainLabels)
                                                        .addComponent(resourceLabels))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel1)
                                                .addGap(168, 168, 168))))
                );
        }// </editor-fold>//GEN-END:initComponents

    private void startLayoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startLayoutActionPerformed
    }//GEN-LAST:event_startLayoutActionPerformed

    private void clientLabelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientLabelsActionPerformed
    }//GEN-LAST:event_clientLabelsActionPerformed

    private void hostLabelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostLabelsActionPerformed
    }//GEN-LAST:event_hostLabelsActionPerformed

    private void resourceLabelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resourceLabelsActionPerformed
    }//GEN-LAST:event_resourceLabelsActionPerformed

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		openWebpage(jButton1.getToolTipText());
        }//GEN-LAST:event_jButton1ActionPerformed

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		openWebpage(jButton2.getToolTipText());
        }//GEN-LAST:event_jButton2ActionPerformed

        private void restFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restFieldActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_restFieldActionPerformed

        private void portFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portFieldActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_portFieldActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        protected javax.swing.JCheckBox clientLabels;
        protected javax.swing.JCheckBox domainLabels;
        protected javax.swing.JCheckBox hostLabels;
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTextArea jTextArea1;
        protected javax.swing.JTextField portField;
        private javax.swing.JLabel portLabel;
        protected javax.swing.JCheckBox resourceLabels;
        protected javax.swing.JTextField restField;
        private javax.swing.JLabel restLabel;
        public javax.swing.JCheckBox startLayout;
        // End of variables declaration//GEN-END:variables
}
