package com.nathansteinmeyer.weightedbridgingcentrality;

/**
 *
 * @author Nathan Steinmeyer
 */
public class WeightedBridgingCentralityMetricPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = -3590479963190614570L;

    public WeightedBridgingCentralityMetricPanel() {
        initComponents();
    }

    public boolean isDirected() {
        return isDirectedCheckBox.isSelected();
    }

    public void setDirected(boolean directed) {
        isDirectedCheckBox.setSelected(directed);
    }

    public void directedCheckBox(boolean enabled) {
        isDirectedCheckBox.setEnabled(enabled);
        isDirectedLabel.setEnabled(enabled);
    }

    public boolean isNormalized() {
        return isNormalizedCheckBox.isSelected();
    }

    public void setNormalized(boolean normalized) {
        isNormalizedCheckBox.setSelected(normalized);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new org.jdesktop.swingx.JXHeader();
        isDirectedCheckBox = new javax.swing.JCheckBox();
        isDirectedLabel = new javax.swing.JLabel();
        isNormalizedCheckBox = new javax.swing.JCheckBox();
        isNormalizedLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(500, 280));

        header.setDescription(org.openide.util.NbBundle.getMessage(WeightedBridgingCentralityMetricPanel.class, "WeightedBridgingCentralityMetricPanel.header.description")); // NOI18N
        header.setTitle(org.openide.util.NbBundle.getMessage(WeightedBridgingCentralityMetricPanel.class, "WeightedBridgingCentralityMetricPanel.header.title")); // NOI18N

        isDirectedLabel.setText(org.openide.util.NbBundle.getMessage(WeightedBridgingCentralityMetricPanel.class, "WeightedBridgingCentralityMetricPanel.isDirectedLabel.text")); // NOI18N

        isNormalizedLabel.setText(org.openide.util.NbBundle.getMessage(WeightedBridgingCentralityMetricPanel.class, "WeightedBridgingCentralityMetricPanel.isNormalizedLabel.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(isDirectedCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isDirectedLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(isNormalizedCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isNormalizedLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isDirectedCheckBox)
                    .addComponent(isDirectedLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isNormalizedCheckBox)
                    .addComponent(isNormalizedLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXHeader header;
    private javax.swing.JCheckBox isDirectedCheckBox;
    private javax.swing.JLabel isDirectedLabel;
    private javax.swing.JCheckBox isNormalizedCheckBox;
    private javax.swing.JLabel isNormalizedLabel;
    // End of variables declaration//GEN-END:variables
}
