package nl.liacs.takesstatistics;

import org.gephi.graph.api.GraphController;
import org.openide.util.Lookup;

public class DiameterMetricPanel extends javax.swing.JPanel {

    /**
     * Creates new form DiameterMetricPanel2
     */
    public DiameterMetricPanel() {
        initComponents();
        
        // Disable directed option (and select undirected) if graph is directed
        GraphController gc = Lookup.getDefault().lookup(GraphController.class);
        if (gc.getGraphModel().isUndirected()) {
            directedRadioBtn.setEnabled(false);
            undirectedRadioBtn.setSelected(true);
        }
    }
    
    
    public void setDirected(boolean b) {
        directedRadioBtn.setSelected(b);
    }
    
    public boolean isDirected() {
        return directedRadioBtn.isSelected();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        directedBtnGroup = new javax.swing.ButtonGroup();
        header = new org.jdesktop.swingx.JXHeader();
        directedRadioBtn = new javax.swing.JRadioButton();
        undirectedRadioBtn = new javax.swing.JRadioButton();

        header.setDescription(org.openide.util.NbBundle.getMessage(DiameterMetricPanel.class, "DiameterMetricPanel.header.description")); // NOI18N
        header.setTitle(org.openide.util.NbBundle.getMessage(DiameterMetricPanel.class, "DiameterMetricPanel.header.title")); // NOI18N

        directedBtnGroup.add(directedRadioBtn);
        directedRadioBtn.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(directedRadioBtn, org.openide.util.NbBundle.getMessage(DiameterMetricPanel.class, "DiameterMetricPanel.directedRadioBtn.text")); // NOI18N
        directedRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directedRadioBtnActionPerformed(evt);
            }
        });

        directedBtnGroup.add(undirectedRadioBtn);
        org.openide.awt.Mnemonics.setLocalizedText(undirectedRadioBtn, org.openide.util.NbBundle.getMessage(DiameterMetricPanel.class, "DiameterMetricPanel.undirectedRadioBtn.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(directedRadioBtn)
                    .addComponent(undirectedRadioBtn))
                .addContainerGap(579, Short.MAX_VALUE))
            .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(directedRadioBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(undirectedRadioBtn)
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void directedRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directedRadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_directedRadioBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup directedBtnGroup;
    private javax.swing.JRadioButton directedRadioBtn;
    private org.jdesktop.swingx.JXHeader header;
    private javax.swing.JRadioButton undirectedRadioBtn;
    // End of variables declaration//GEN-END:variables
}
