/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package fr.totetmatt.blueskygephi;

import fr.totetmatt.blueskygephi.atproto.AtProtoException;
import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.util.Arrays;
import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.Icon;
import javax.swing.UIManager;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.awt.NotificationDisplayer;
import org.openide.util.Exceptions;
import org.openide.util.Lookup;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;

/**
 *
 * @author totetmatt
 */
@TopComponent.Description(preferredID = "BlueskyGephiMainPanel",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "layoutmode", openAtStartup = true, roles = {"overview"}, position = 2)
@ActionID(category = "Window", id = "fr.totetmatt.blueskygephi.BlueskyGephiMainPanel")
@ActionReference(path = "Menu/Window", position = 334)
@TopComponent.OpenActionRegistration(displayName = "#CTL_BlueskyGephiMainPanel",
        preferredID = "BlueskyGephiMainPanel")
public class BlueskyGephiMainPanel extends TopComponent {
    protected static final Logger consoleLogger = Logger.getLogger(BlueskyGephiMainPanel.class.getName());
    private static final Logger logger = Logger.getLogger(BlueskyGephiMainPanel.class.getName());
    private BlueskyGephi blueskyGephi;
    /**
     * Creates new form BlueskyGephiMainPanel
     */
    public BlueskyGephiMainPanel() {
        initComponents();
        setName(NbBundle.getMessage(BlueskyGephiMainPanel.class, "CTL_BlueskyGephiMainPanel"));
        setToolTipText(NbBundle.getMessage(BlueskyGephiMainPanel.class, "HINT_BlueskyGephiMainPanel"));
        blueskyGephi = Lookup.getDefault().lookup(BlueskyGephi.class);
        if (blueskyGephi == null) {
            logger.warning("BlueskyGephi service not available");
            return;
        }
        credentialsHostField.setText(blueskyGephi.getHost());
        credentialsHandleField.setText(blueskyGephi.getHandle());
        credentialsPasswordField.setText(blueskyGephi.getPassword());
        handleSearchTextArea.setText(blueskyGephi.getQuery());
        isFollowersActivated.setSelected(blueskyGephi.getIsFollowersActive());
        isFollowsActivated.setSelected(blueskyGephi.getIsFollowsActive());
        isDeepSearch.setSelected(blueskyGephi.getIsDeepSearch());
        limitCrawlCheckbox.setSelected(blueskyGephi.getIsLimitCrawlActive());
        limitCrawlSpinner.setValue(blueskyGephi.getLimitCrawl()*100);
        limitCrawlSpinner.setEnabled(limitCrawlCheckbox.isSelected());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        credentialsPanel = new javax.swing.JPanel();
        credentialsHostLabel = new javax.swing.JLabel();
        credentialsHostField = new javax.swing.JTextField();
        credentialsHandleLabel = new javax.swing.JLabel();
        credentialsHandleField = new javax.swing.JTextField();
        credentialsPasswordLabel = new javax.swing.JLabel();
        credentialsPasswordField = new javax.swing.JPasswordField();
        credentialsConnectButton = new javax.swing.JButton();
        credentialsCheckButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        handleSearchTextArea = new javax.swing.JTextArea();
        fetchLabel = new javax.swing.JLabel();
        isFollowersActivated = new javax.swing.JCheckBox();
        isFollowsActivated = new javax.swing.JCheckBox();
        runFetchButton = new javax.swing.JButton();
        isDeepSearch = new javax.swing.JCheckBox();
        limitCrawlCheckbox = new javax.swing.JCheckBox();
        limitCrawlSpinner = new javax.swing.JSpinner();

        setToolTipText(org.openide.util.NbBundle.getMessage(BlueskyGephiMainPanel.class, "BlueskyGephiMainPanel.toolTipText")); // NOI18N
        setName("Bluesky Gephi"); // NOI18N

        credentialsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(BlueskyGephiMainPanel.class, "BlueskyGephiMainPanel.credentialsPanel.border.title"))); // NOI18N
        credentialsPanel.setToolTipText(org.openide.util.NbBundle.getMessage(BlueskyGephiMainPanel.class, "BlueskyGephiMainPanel.Credentials.toolTipText")); // NOI18N
        credentialsPanel.setName("Credentials"); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(credentialsHostLabel, org.openide.util.NbBundle.getMessage(BlueskyGephiMainPanel.class, "BlueskyGephiMainPanel.credentialsHostLabel.text")); // NOI18N

        credentialsHostField.setText(org.openide.util.NbBundle.getMessage(BlueskyGephiMainPanel.class, "BlueskyGephiMainPanel.credentialsHostField.text")); // NOI18N
        credentialsHostField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                credentialsHostFieldActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(credentialsHandleLabel, org.openide.util.NbBundle.getMessage(BlueskyGephiMainPanel.class, "BlueskyGephiMainPanel.credentialsHandleLabel.text")); // NOI18N

        credentialsHandleField.setText(org.openide.util.NbBundle.getMessage(BlueskyGephiMainPanel.class, "BlueskyGephiMainPanel.credentialsHandleField.text")); // NOI18N

        credentialsPasswordLabel.setForeground(new java.awt.Color(0, 51, 255));
        org.openide.awt.Mnemonics.setLocalizedText(credentialsPasswordLabel, org.openide.util.NbBundle.getMessage(BlueskyGephiMainPanel.class, "BlueskyGephiMainPanel.credentialsPasswordLabel.text")); // NOI18N
        credentialsPasswordLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        credentialsPasswordLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                credentialsPasswordLabelMouseClicked(evt);
            }
        });

        credentialsPasswordField.setText(org.openide.util.NbBundle.getMessage(BlueskyGephiMainPanel.class, "BlueskyGephiMainPanel.credentialsPasswordField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(credentialsConnectButton, org.openide.util.NbBundle.getMessage(BlueskyGephiMainPanel.class, "BlueskyGephiMainPanel.credentialsConnectButton.text")); // NOI18N
        credentialsConnectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                credentialsConnectButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(credentialsCheckButton, org.openide.util.NbBundle.getMessage(BlueskyGephiMainPanel.class, "BlueskyGephiMainPanel.credentialsCheckButton.text")); // NOI18N
        credentialsCheckButton.setToolTipText(org.openide.util.NbBundle.getMessage(BlueskyGephiMainPanel.class, "BlueskyGephiMainPanel.credentialsCheckButton.toolTipText")); // NOI18N
        credentialsCheckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                credentialsCheckButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout credentialsPanelLayout = new javax.swing.GroupLayout(credentialsPanel);
        credentialsPanel.setLayout(credentialsPanelLayout);
        credentialsPanelLayout.setHorizontalGroup(
            credentialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(credentialsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(credentialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(credentialsConnectButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(credentialsPanelLayout.createSequentialGroup()
                        .addGroup(credentialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(credentialsHandleLabel)
                            .addComponent(credentialsHostLabel)
                            .addComponent(credentialsPasswordLabel))
                        .addGap(18, 18, 18)
                        .addGroup(credentialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(credentialsHandleField, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(credentialsPasswordField)
                            .addGroup(credentialsPanelLayout.createSequentialGroup()
                                .addComponent(credentialsHostField, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(credentialsCheckButton)))))
                .addContainerGap())
        );
        credentialsPanelLayout.setVerticalGroup(
            credentialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, credentialsPanelLayout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addGroup(credentialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(credentialsHandleLabel)
                    .addComponent(credentialsHandleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(credentialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(credentialsHostLabel)
                    .addComponent(credentialsHostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(credentialsCheckButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(credentialsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(credentialsPasswordLabel)
                    .addComponent(credentialsPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(credentialsConnectButton))
        );

        handleSearchTextArea.setColumns(20);
        handleSearchTextArea.setRows(5);
        jScrollPane1.setViewportView(handleSearchTextArea);

        org.openide.awt.Mnemonics.setLocalizedText(fetchLabel, org.openide.util.NbBundle.getMessage(BlueskyGephiMainPanel.class, "BlueskyGephiMainPanel.fetchLabel.text")); // NOI18N

        isFollowersActivated.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(isFollowersActivated, org.openide.util.NbBundle.getMessage(BlueskyGephiMainPanel.class, "BlueskyGephiMainPanel.isFollowersActivated.text")); // NOI18N
        isFollowersActivated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isFollowersActivatedActionPerformed(evt);
            }
        });

        isFollowsActivated.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(isFollowsActivated, org.openide.util.NbBundle.getMessage(BlueskyGephiMainPanel.class, "BlueskyGephiMainPanel.isFollowsActivated.text")); // NOI18N
        isFollowsActivated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isFollowsActivatedActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(runFetchButton, org.openide.util.NbBundle.getMessage(BlueskyGephiMainPanel.class, "BlueskyGephiMainPanel.runFetchButton.text")); // NOI18N
        runFetchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runFetchButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(isDeepSearch, org.openide.util.NbBundle.getMessage(BlueskyGephiMainPanel.class, "BlueskyGephiMainPanel.isDeepSearch.text")); // NOI18N
        isDeepSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isDeepSearchActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(limitCrawlCheckbox, org.openide.util.NbBundle.getMessage(BlueskyGephiMainPanel.class, "BlueskyGephiMainPanel.limitCrawlCheckbox.text")); // NOI18N
        limitCrawlCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limitCrawlCheckboxActionPerformed(evt);
            }
        });

        limitCrawlSpinner.setToolTipText(org.openide.util.NbBundle.getMessage(BlueskyGephiMainPanel.class, "BlueskyGephiMainPanel.limitCrawlSpinner.toolTipText")); // NOI18N
        limitCrawlSpinner.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                limitCrawlSpinnerPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fetchLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(isFollowersActivated)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(isFollowsActivated))
                            .addComponent(isDeepSearch))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(limitCrawlSpinner)
                            .addComponent(limitCrawlCheckbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(runFetchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                    .addComponent(credentialsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(credentialsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fetchLabel)
                    .addComponent(isFollowersActivated)
                    .addComponent(isFollowsActivated)
                    .addComponent(limitCrawlCheckbox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isDeepSearch)
                    .addComponent(limitCrawlSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(runFetchButton)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        limitCrawlSpinner.getAccessibleContext().setAccessibleDescription(org.openide.util.NbBundle.getMessage(BlueskyGephiMainPanel.class, "BlueskyGephiMainPanel.limitCrawlSpinner.AccessibleContext.accessibleDescription")); // NOI18N
    }// </editor-fold>//GEN-END:initComponents

    private void isFollowersActivatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isFollowersActivatedActionPerformed
        blueskyGephi.setIsFollowersActive(isFollowersActivated.isSelected());
    }//GEN-LAST:event_isFollowersActivatedActionPerformed

    private void credentialsConnectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_credentialsConnectButtonActionPerformed
        final String host = credentialsHostField.getText();
        final String handle = credentialsHandleField.getText();
        final String password = String.valueOf(credentialsPasswordField.getPassword());
        // Do the network call off the EDT so a slow or failing login never freezes the UI.
        credentialsConnectButton.setEnabled(false);
        credentialsConnectButton.setBackground(Color.ORANGE);
        new javax.swing.SwingWorker<Boolean, Void>() {
            @Override
            protected Boolean doInBackground() {
                return blueskyGephi.connect(host, handle, password);
            }

            @Override
            protected void done() {
                boolean connected = false;
                try {
                    connected = get();
                } catch (InterruptedException ex) {
                    Thread.currentThread().interrupt();
                } catch (java.util.concurrent.ExecutionException ex) {
                    Exceptions.printStackTrace(ex);
                }
                credentialsConnectButton.setBackground(connected ? Color.GREEN : Color.RED);
                credentialsConnectButton.setEnabled(true);
            }
        }.execute();
    }//GEN-LAST:event_credentialsConnectButtonActionPerformed

    private void credentialsCheckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_credentialsCheckButtonActionPerformed
        final String handle = credentialsHandleField.getText();
        // Resolve the account's PDS host off the EDT so a slow lookup never freezes the UI.
        credentialsCheckButton.setEnabled(false);
        credentialsCheckButton.setBackground(Color.ORANGE);
        new javax.swing.SwingWorker<String, Void>() {
            @Override
            protected String doInBackground() {
                return blueskyGephi.resolveHostFromHandle(handle);
            }

            @Override
            protected void done() {
                try {
                    String host = get();
                    credentialsHostField.setText(host);
                    credentialsCheckButton.setBackground(Color.GREEN);
                } catch (InterruptedException ex) {
                    Thread.currentThread().interrupt();
                    credentialsCheckButton.setBackground(Color.RED);
                } catch (ExecutionException ex) {
                    credentialsCheckButton.setBackground(Color.RED);
                    Throwable cause = (ex.getCause() != null) ? ex.getCause() : ex;
                    String detail = (cause instanceof AtProtoException)
                            ? ((AtProtoException) cause).getUserMessageWithContent()
                            : String.valueOf(cause.getMessage());
                    consoleLogger.warning("Host check failed for \"" + handle + "\": " + detail);
                    notifyError("Bluesky: could not determine host from handle", detail);
                } finally {
                    credentialsCheckButton.setEnabled(true);
                }
            }
        }.execute();
    }//GEN-LAST:event_credentialsCheckButtonActionPerformed

    private void notifyError(String title, String detail) {
        Icon icon = UIManager.getIcon("OptionPane.warningIcon");
        if (icon == null) {
            icon = new javax.swing.ImageIcon(
                    new java.awt.image.BufferedImage(16, 16, java.awt.image.BufferedImage.TYPE_INT_ARGB));
        }
        NotificationDisplayer.getDefault().notify(title, icon, detail, null, NotificationDisplayer.Priority.HIGH);
    }

    private void runFetchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runFetchButtonActionPerformed
         blueskyGephi.setQuery(handleSearchTextArea.getText());
         List<String> actors = Arrays.asList(handleSearchTextArea.getText().split("\\n"))
                .stream()
                .map(x -> x.trim())
                .collect(Collectors.toList());
       blueskyGephi.fetchFollowerFollowsFromActors(actors);
        
    }//GEN-LAST:event_runFetchButtonActionPerformed

    private void isFollowsActivatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isFollowsActivatedActionPerformed
        blueskyGephi.setIsFollowsActive(isFollowsActivated.isSelected()); 
    }//GEN-LAST:event_isFollowsActivatedActionPerformed

    private void credentialsPasswordLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_credentialsPasswordLabelMouseClicked
        try {
            Desktop.getDesktop().browse(URI.create("https://bsky.app/settings/app-passwords"));        // TODO add your handling code here:
        } catch (IOException ex) {
            Exceptions.printStackTrace(ex);
        }
    }//GEN-LAST:event_credentialsPasswordLabelMouseClicked

    private void isDeepSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isDeepSearchActionPerformed
        blueskyGephi.setIsDeepSearch(isDeepSearch.isSelected());
    }//GEN-LAST:event_isDeepSearchActionPerformed

    private void limitCrawlCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limitCrawlCheckboxActionPerformed
            blueskyGephi.setIsLimitCrawlActive(limitCrawlCheckbox.isSelected());
            limitCrawlSpinner.setEnabled(limitCrawlCheckbox.isSelected());
            
    }//GEN-LAST:event_limitCrawlCheckboxActionPerformed

    private void limitCrawlSpinnerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_limitCrawlSpinnerPropertyChange
            blueskyGephi.setLimitCrawl(Math.max(1,((int)limitCrawlSpinner.getValue())/100));
    }//GEN-LAST:event_limitCrawlSpinnerPropertyChange

    private void credentialsHostFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_credentialsHostFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_credentialsHostFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton credentialsCheckButton;
    private javax.swing.JButton credentialsConnectButton;
    private javax.swing.JTextField credentialsHandleField;
    private javax.swing.JLabel credentialsHandleLabel;
    private javax.swing.JTextField credentialsHostField;
    private javax.swing.JLabel credentialsHostLabel;
    private javax.swing.JPanel credentialsPanel;
    private javax.swing.JPasswordField credentialsPasswordField;
    private javax.swing.JLabel credentialsPasswordLabel;
    private javax.swing.JLabel fetchLabel;
    private javax.swing.JTextArea handleSearchTextArea;
    private javax.swing.JCheckBox isDeepSearch;
    private javax.swing.JCheckBox isFollowersActivated;
    private javax.swing.JCheckBox isFollowsActivated;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox limitCrawlCheckbox;
    private javax.swing.JSpinner limitCrawlSpinner;
    private javax.swing.JButton runFetchButton;
    // End of variables declaration//GEN-END:variables
}
