/*
  Copyright (C) 2016 Gary Briggs

  This software is provided 'as-is', without any express or implied
  warranty.  In no event will the authors be held liable for any damages
  arising from the use of this software.

  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely, subject to the following restrictions:

  1. The origin of this software must not be misrepresented; you must not
     claim that you wrote the original software. If you use this software
     in a product, an acknowledgment in the product documentation would be
     appreciated but is not required.
  2. Altered source versions must be plainly marked as such, and must not be
     misrepresented as being the original software.
  3. This notice may not be removed or altered from any source distribution.

        Gary Briggs <chunky@icculus.org>
*/

/*
 * GraphvizUIPanel.java
 *
 * Created on Oct 23, 2011, 4:35:36 PM
 */
package org.icculus.chunky.gephigraphviz;

import java.awt.Desktop;
import java.net.URI;

/**
 *
 * @author chunky
 */
public class GraphvizUIPanel extends javax.swing.JPanel {

    GraphvizLayout gvl = null;
    
    /** Creates new form GraphvizUIPanel */
    public GraphvizUIPanel(GraphvizLayout gvl) {
        initComponents();
        this.gvl = gvl;
        
        algoCombo.getModel().setSelectedItem(gvl.getAlgoName());
        rankdirCombo.getModel().setSelectedItem(gvl.getRankDir());
        overlapCombo.getModel().setSelectedItem(gvl.getOverlap());
        dotBinary.setText(gvl.getDotBinary());
        concentrateCheck.setSelected(gvl.isConcentrate());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        algoCombo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        rankdirCombo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        concentrateCheck = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        overlapCombo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        dotBinary = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        jButton1.setText(org.openide.util.NbBundle.getMessage(GraphvizUIPanel.class, "GraphvizUIPanel.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(jButton1, gridBagConstraints);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(GraphvizUIPanel.class, "GraphvizUIPanel.jLabel1.text_1")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jLabel1, gridBagConstraints);

        algoCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "dot", "sfdp", "fdp", "neato", "twopi", "osage", "circo", "patchwork", "nop" }));
        algoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                algoComboActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(algoCombo, gridBagConstraints);

        jLabel2.setText(org.openide.util.NbBundle.getMessage(GraphvizUIPanel.class, "GraphvizUIPanel.jLabel2.text_1")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jLabel2, gridBagConstraints);

        rankdirCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TB", "LR", "BT", "RL" }));
        rankdirCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rankdirComboActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(rankdirCombo, gridBagConstraints);

        jLabel4.setText(org.openide.util.NbBundle.getMessage(GraphvizUIPanel.class, "GraphvizUIPanel.jLabel4.text_1")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jLabel4, gridBagConstraints);

        concentrateCheck.setSelected(true);
        concentrateCheck.setText(org.openide.util.NbBundle.getMessage(GraphvizUIPanel.class, "GraphvizUIPanel.concentrateCheck.text_1")); // NOI18N
        concentrateCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concentrateCheckActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(concentrateCheck, gridBagConstraints);

        jLabel5.setText(org.openide.util.NbBundle.getMessage(GraphvizUIPanel.class, "GraphvizUIPanel.jLabel5.text_1")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jLabel5, gridBagConstraints);

        overlapCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "true", "scale", "false", "prism", "prism0", "scalexy", "compress", "vpsc", "ortho", "orthoxy", "orthoyx", "ortho_yx", "portho", "porthoxy", "porthoyx", "portho_yx", "ipsep" }));
        overlapCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overlapComboActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(overlapCombo, gridBagConstraints);

        jLabel3.setText(org.openide.util.NbBundle.getMessage(GraphvizUIPanel.class, "GraphvizUIPanel.jLabel3.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jLabel3, gridBagConstraints);

        dotBinary.setText(org.openide.util.NbBundle.getMessage(GraphvizUIPanel.class, "GraphvizUIPanel.dotBinary.text")); // NOI18N
        dotBinary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotBinaryActionPerformed(evt);
            }
        });
        dotBinary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dotBinaryKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dotBinaryKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(dotBinary, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void algoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_algoComboActionPerformed
        gvl.setAlgoName((String)algoCombo.getModel().getSelectedItem());
    }//GEN-LAST:event_algoComboActionPerformed

    private void rankdirComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rankdirComboActionPerformed
        gvl.setRankDir((String)rankdirCombo.getModel().getSelectedItem());
    }//GEN-LAST:event_rankdirComboActionPerformed

    private void concentrateCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concentrateCheckActionPerformed
        gvl.setConcentrate(concentrateCheck.isSelected());
    }//GEN-LAST:event_concentrateCheckActionPerformed

    private void overlapComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overlapComboActionPerformed
        gvl.setOverlap((String)overlapCombo.getModel().getSelectedItem());
    }//GEN-LAST:event_overlapComboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Desktop desktop = Desktop.getDesktop();
        try {
            URI specUrl = new URI("http://www.graphviz.org/doc/info/attrs.html");
            desktop.browse(specUrl);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void dotBinaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotBinaryActionPerformed
        gvl.setDotBinary(dotBinary.getText());
    }//GEN-LAST:event_dotBinaryActionPerformed

    private void dotBinaryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dotBinaryKeyTyped
        gvl.setDotBinary(dotBinary.getText());
    }//GEN-LAST:event_dotBinaryKeyTyped

    private void dotBinaryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dotBinaryKeyReleased
        gvl.setDotBinary(dotBinary.getText());
    }//GEN-LAST:event_dotBinaryKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox algoCombo;
    private javax.swing.JCheckBox concentrateCheck;
    private javax.swing.JTextField dotBinary;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox overlapCombo;
    private javax.swing.JComboBox rankdirCombo;
    // End of variables declaration//GEN-END:variables
}

