/*
 * Copyright (c) 2011, INRIA
 * All rights reserved.
 */
package fr.inria.wimmics.semanticweb.filter.instance;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import org.gephi.filters.spi.FilterProperty;

/**
 *
 * @author Erwan Demairy <Erwan.Demairy@inria.fr>
 */
public class InstanceFilterPanel extends javax.swing.JPanel implements ActionListener {

    private static final long serialVersionUID = -6108289528761360770L;
    private final InstanceFilter filter;

    public InstanceFilterPanel(InstanceFilter filter) {
        this.filter = filter;
        initComponents();
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        FilterProperty typeToFilter = filter.getProperties()[0];
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 498, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 36, Short.MAX_VALUE)
                );
        }// </editor-fold>//GEN-END:initComponents
        // Variables declaration - do not modify//GEN-BEGIN:variables
        // End of variables declaration//GEN-END:variables
}
