/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package totetmatt.gephi.twitter;

import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author totetmatt
 */
public class TwitterCredentialDialog extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form TwitterCredentialDialog
     */
    public TwitterCredentialDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        credential_goto_twitter_button = new javax.swing.JButton();
        credential_consumer_key_label = new javax.swing.JLabel();
        credential_consumer_secret_label = new javax.swing.JLabel();
        credential_consumer_key_field = new javax.swing.JTextField();
        credential_consumer_secret_field = new javax.swing.JTextField();
        credential_access_token_label = new javax.swing.JLabel();
        credential_access_token_secret_label = new javax.swing.JLabel();
        credential_access_token_field = new javax.swing.JTextField();
        credential_access_token_secret_field = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setTitle(org.openide.util.NbBundle.getMessage(TwitterCredentialDialog.class, "TwitterCredentialDialog.title")); // NOI18N
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(400, 182));
        setMinimumSize(new java.awt.Dimension(400, 182));
        setModal(true);
        setName("Twitter API Credential"); // NOI18N
        setSize(new java.awt.Dimension(400, 182));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(okButton, org.openide.util.NbBundle.getMessage(TwitterCredentialDialog.class, "TwitterCredentialDialog.okButton.text")); // NOI18N
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(cancelButton, org.openide.util.NbBundle.getMessage(TwitterCredentialDialog.class, "TwitterCredentialDialog.cancelButton.text")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(credential_goto_twitter_button, org.openide.util.NbBundle.getMessage(TwitterCredentialDialog.class, "TwitterCredentialDialog.credential_goto_twitter_button.text")); // NOI18N
        credential_goto_twitter_button.setActionCommand(org.openide.util.NbBundle.getMessage(TwitterCredentialDialog.class, "TwitterCredentialDialog.credential_goto_twitter_button.actionCommand")); // NOI18N
        credential_goto_twitter_button.setBorder(null);
        credential_goto_twitter_button.setBorderPainted(false);
        credential_goto_twitter_button.setContentAreaFilled(false);
        credential_goto_twitter_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                credential_goto_twitter_buttonActionPerformed(evt);
            }
        });

        credential_consumer_key_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.openide.awt.Mnemonics.setLocalizedText(credential_consumer_key_label, org.openide.util.NbBundle.getMessage(TwitterCredentialDialog.class, "TwitterCredentialDialog.credential_consumer_key_label.text")); // NOI18N

        credential_consumer_secret_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.openide.awt.Mnemonics.setLocalizedText(credential_consumer_secret_label, org.openide.util.NbBundle.getMessage(TwitterCredentialDialog.class, "TwitterCredentialDialog.credential_consumer_secret_label.text")); // NOI18N

        credential_consumer_key_field.setText(org.openide.util.NbBundle.getMessage(TwitterCredentialDialog.class, "TwitterCredentialDialog.credential_consumer_key_field.text")); // NOI18N

        credential_consumer_secret_field.setText(org.openide.util.NbBundle.getMessage(TwitterCredentialDialog.class, "TwitterCredentialDialog.credential_consumer_secret_field.text")); // NOI18N

        credential_access_token_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.openide.awt.Mnemonics.setLocalizedText(credential_access_token_label, org.openide.util.NbBundle.getMessage(TwitterCredentialDialog.class, "TwitterCredentialDialog.credential_access_token_label.text")); // NOI18N

        credential_access_token_secret_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.openide.awt.Mnemonics.setLocalizedText(credential_access_token_secret_label, org.openide.util.NbBundle.getMessage(TwitterCredentialDialog.class, "TwitterCredentialDialog.credential_access_token_secret_label.text")); // NOI18N

        credential_access_token_field.setText(org.openide.util.NbBundle.getMessage(TwitterCredentialDialog.class, "TwitterCredentialDialog.credential_access_token_field.text")); // NOI18N

        credential_access_token_secret_field.setText(org.openide.util.NbBundle.getMessage(TwitterCredentialDialog.class, "TwitterCredentialDialog.credential_access_token_secret_field.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(credential_consumer_secret_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(credential_consumer_key_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(credential_consumer_key_field)
                            .addComponent(credential_consumer_secret_field)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(credential_goto_twitter_button, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(credential_access_token_secret_label, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(credential_access_token_label, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(credential_access_token_field, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(credential_access_token_secret_field)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelButton)))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(credential_consumer_key_label)
                    .addComponent(credential_consumer_key_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(credential_consumer_secret_label)
                    .addComponent(credential_consumer_secret_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(credential_access_token_label)
                    .addComponent(credential_access_token_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(credential_access_token_secret_label)
                    .addComponent(credential_access_token_secret_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cancelButton)
                        .addComponent(okButton))
                    .addComponent(credential_goto_twitter_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getRootPane().setDefaultButton(okButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void credential_goto_twitter_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_credential_goto_twitter_buttonActionPerformed
        if (Desktop.isDesktopSupported()) {
            try {
                Desktop.getDesktop().browse(new URI("https://apps.twitter.com/"));
            } catch (IOException e) {
                Logger.getLogger(MainTwitterWindows.class.getName()).log(Level.SEVERE, null, e);
            } catch (URISyntaxException ex) {
                Logger.getLogger(MainTwitterWindows.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            Logger.getLogger(MainTwitterWindows.class.getName()).log(Level.SEVERE, null, new Exception("Desktop method isn't supported"));
        }
    }//GEN-LAST:event_credential_goto_twitter_buttonActionPerformed
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }
    
    public void setCredentialProperty(CredentialProperty property){
        credential_consumer_key_field.setText(property.getConsumerKey());
        credential_consumer_secret_field.setText(property.getConsumerSecret());
        credential_access_token_field.setText(property.getToken());
        credential_access_token_secret_field.setText(property.getTokenSecret());  
    }
    
    public CredentialProperty getCredentialProperty(){
        CredentialProperty newCredential = new CredentialProperty();
        newCredential.setConsumerKey(credential_consumer_key_field.getText().trim());
        newCredential.setConsumerSecret(credential_consumer_secret_field.getText().trim());
        newCredential.setToken(credential_access_token_field.getText().trim());
        newCredential.setTokenSecret(credential_access_token_secret_field.getText().trim());
        return newCredential;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField credential_access_token_field;
    private javax.swing.JLabel credential_access_token_label;
    private javax.swing.JTextField credential_access_token_secret_field;
    private javax.swing.JLabel credential_access_token_secret_label;
    private javax.swing.JTextField credential_consumer_key_field;
    private javax.swing.JLabel credential_consumer_key_label;
    private javax.swing.JTextField credential_consumer_secret_field;
    private javax.swing.JLabel credential_consumer_secret_label;
    private javax.swing.JButton credential_goto_twitter_button;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
