name: build

on:
  push:
    branches-ignore:
      - master-forge
      - master
      - parent-pom
      - gh-pages

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build and validate project
        run: mvn -B package --file pom.xml