name: release-pom

on:
  push:
    branches: [ parent-pom ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: modules
    steps:
      - uses: actions/checkout@v6
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: central
          server-username: OSSRH_USER
          server-password: OSSRH_PASS
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE
      - name: Build and validate project
        run: mvn -B deploy -P release-pom --file pom.xml
        env:
          OSSRH_USER: ${{ secrets.OSSRH_TOKEN_USER }}
          OSSRH_PASS: ${{ secrets.OSSRH_TOKEN_PASSWD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}